
import { Translation, Language, Gender } from './types';

export const MODEL_NAME = 'gemini-3-pro-image-preview';

export const CLOTHING_PRESETS: Record<Language, Record<Gender, string[]>> = {
  en: {
    male: [
      "Classic Navy Blue Business Suit, White Shirt, Red Tie",
      "Modern Charcoal Grey Suit, Light Blue Shirt, No Tie",
      "Black Tuxedo, White Wing-tip Shirt, Black Bow Tie",
      "Smart Casual: Beige Blazer, White Crew-neck T-Shirt",
      "Tech Executive: Black T-Shirt, Dark Grey Hoodie",
      "Business Professional: White Button-down Shirt, Rolled Sleeves",
      "Relaxed Business: Checkered Button-down Shirt, Navy Sweater Vest",
      "Sophisticated: Black Turtle Neck Sweater, Grey Wool Blazer",
      "Creative: Denim Shirt, Brown Leather Jacket",
      "Medical Professional: White Lab Coat, Blue Scrub Top"
    ],
    female: [
      "Classic Black Business Suit, White Button-down Shirt",
      "Modern Navy Blue Blazer, Cream Silk Camisole",
      "Smart Casual: White Structured Blazer, Black Top",
      "Elegant: Emerald Green Professional Shift Dress",
      "Creative Professional: Patterned Blouse, Cardigan",
      "Tech Style: Grey Hoodie, Black Minimalist T-Shirt",
      "Chic Professional: Beige Trench Coat Style Dress",
      "Medical Professional: White Lab Coat, Teal Scrub Top",
      "Soft Professional: Pastel Pink Blouse, Pearl Necklace",
      "Executive: Charcoal Grey Pinstripe Suit, High-neck Top"
    ]
  },
  'zh-TW': {
    male: [
      "經典深藍色商務西裝，白襯衫，紅領帶",
      "現代炭灰色西裝，淺藍襯衫，無領帶",
      "黑色燕尾服，白色翼領襯衫，黑色領結",
      "智能休閒：米色西裝外套，白色圓領T恤",
      "科技高管風：黑色T恤，深灰色連帽衫",
      "商務專業：白色鈕扣襯衫，捲袖",
      "輕鬆商務：格紋鈕扣襯衫，深藍色毛衣背心",
      "成熟穩重：黑色高領毛衣，灰色羊毛西裝外套",
      "創意風格：牛仔襯衫，棕色皮夾克",
      "醫療專業：白袍，藍色刷手服"
    ],
    female: [
      "經典黑色商務套裝，白色鈕扣襯衫",
      "現代深藍色西裝外套，奶油色絲綢背心",
      "智能休閒：白色結構西裝外套，黑色上衣",
      "優雅風格：祖母綠色專業直筒連衣裙",
      "創意專業：圖案襯衫，開襟羊毛衫",
      "科技風格：灰色連帽衫，黑色極簡T恤",
      "時尚專業：米色風衣式連衣裙",
      "醫療專業：白袍，藍綠色刷手服",
      "柔和專業：淡粉色襯衫，珍珠項鍊",
      "高管風格：炭灰色條紋西裝，高領上衣"
    ]
  },
  'zh-CN': {
    male: [
      "经典深蓝色商务西装，白衬衫，红领带",
      "现代炭灰色西装，浅蓝衬衫，无领带",
      "黑色燕尾服，白色翼领衬衫，黑色领结",
      "智能休闲：米色西装外套，白色圆领T恤",
      "科技高管风：黑色T恤，深灰色连帽衫",
      "商务专业：白色纽扣衬衫，卷袖",
      "轻松商务：格纹纽扣衬衫，深蓝色毛衣背心",
      "成熟稳重：黑色高领毛衣，灰色羊毛西装外套",
      "创意风格：牛仔衬衫，棕色皮夹克",
      "医疗专业：白大褂，蓝色刷手服"
    ],
    female: [
      "经典黑色商务套装，白色纽扣衬衫",
      "现代深蓝色西装外套，奶油色丝绸背心",
      "智能休闲：白色结构西装外套，黑色上衣",
      "优雅风格：祖母绿色专业直筒连衣裙",
      "创意专业：图案衬衫，开襟羊毛衫",
      "科技风格：灰色连帽衫，黑色极简T恤",
      "时尚专业：米色风衣式连衣裙",
      "医疗专业：白大褂，蓝绿色刷手服",
      "柔和专业：淡粉色衬衫，珍珠项链",
      "高管风格：炭灰色条纹西装，高领上衣"
    ]
  }
};

export const RANDOM_CLOTHING_ATTRIBUTES = {
  en: {
    styles: ['Avant-garde minimalist', 'High-fashion editorial', 'Ivy League academic', 'Silicon Valley minimalist', 'European sartorial elegance', 'Contemporary urban chic'],
    materials: ['fine cashmere', 'structured wool', 'crisp linen', 'textured tweed', 'heavyweight cotton', 'Italian silk'],
    garments: ['double-breasted blazer', 'mock-neck sweater', 'architectural shirt', 'tailored overcoat', 'knit polo', 'structured vest'],
    details: ['with horn buttons', 'featuring subtle geometric patterns', 'monochrome layering', 'accentuated with a pocket square', 'with a focus on silhouette', 'sharp lapels'],
    vibe: ['soft cinematic lighting', 'dramatic studio shadows', 'natural diffused light', 'clean commercial aesthetic']
  },
  'zh-TW': {
    styles: ['前衛極簡風格', '高級時尚雜誌風', '常春藤學院風', '矽谷極簡主義', '歐洲紳士優雅', '當代都會時髦'],
    materials: ['頂級羊絨', '挺括羊毛', '清爽亞麻', '質感粗花呢', '重磅棉質', '義大利絲綢'],
    garments: ['雙排扣西裝外套', '半高領毛衣', '剪裁獨特的襯衫', '合身大衣', '針織Polo衫', '結構感背心'],
    details: ['搭配牛角扣', '帶有微妙的幾何圖案', '單色系層次穿搭', '點綴口袋巾', '強調輪廓剪裁', '俐落劍領設計'],
    vibe: ['柔和電影光感', '戲劇性攝影棚陰影', '自然漫射光', '潔淨商業美學']
  },
  'zh-CN': {
    styles: ['前卫极简风格', '高级时尚杂志风', '常春藤学院风', '硅谷极简主义', '欧洲绅士优雅', '当代都会时髦'],
    materials: ['顶级羊绒', '挺括羊毛', '清爽亚麻', '质感粗花呢', '重磅棉质', '意大利丝绸'],
    garments: ['双排扣西装外套', '半高领毛衣', '剪裁独特的衬衫', '合身大衣', '针织Polo衫', '结构感背心'],
    details: ['搭配牛角扣', '带有微妙的几何图案', '单色系层次穿搭', '点缀口袋巾', '强调轮廓剪裁', '利落剑领设计'],
    vibe: ['柔和电影光感', '戏剧性摄影棚阴影', '自然漫射光', '洁净商业美学']
  }
};

export const TRANSLATIONS: Record<Language, Translation> = {
  en: {
    title: 'Autron ProPortrait',
    subtitle: 'Professional Studio AI',
    uploadTitle: 'SOURCE MATERIAL',
    uploadDesc: 'Upload Source Image',
    uploadTip: 'REQUIRED: Front-facing, clear lighting.',
    changePhoto: 'Replace Source',
    genderLabel: 'SUBJECT GENDER',
    male: 'Male',
    female: 'Female',
    clothingLabel: 'STYLING DIRECTION',
    clothingPlaceholder: 'Describe the desired look (e.g., Bespoke navy suit, crisp white shirt...)',
    clothingPresetsLabel: 'CURATED LOOKS',
    undo: 'Undo',
    redo: 'Redo',
    randomBtn: 'Surprise Me',
    generateBtn: 'INITIALIZE GENERATION',
    regenerateBtn: 'Regenerate',
    downloadBtn: 'Download Asset',
    anglesTitle: 'ADDITIONAL ANGLES',
    angleLeft45: 'Profile Left',
    angleRight45: 'Profile Right',
    angleFull: 'Full Body',
    angleClose: 'Detailed Portrait',
    historyTitle: 'SESSION ASSETS',
    emptyTitle: 'Studio Ready',
    emptyDesc: 'Import a subject to begin the professional styling session.',
    errorNoImage: 'Source image required.',
    errorApiKey: 'API connection failed.',
    errorEntityNotFound: 'Project invalid.',
    errorGeneric: 'System error.',
    billingLinkText: 'Enterprise/Billing Key Required',
    selectKeyBtn: 'Authenticate',
    retryBtn: 'Retry Connection',
    loading: 'RENDERING...',
    success: 'Render Complete',
    selectPreset: 'Select curated style...',
    footerRights: 'AUTRON GROUP HOLDINGS LTD. © 2025',
    ctaShareTitle: 'Professional Portfolio',
    ctaShareBtn: 'Export to Gallery'
  },
  'zh-TW': {
    title: 'Autron 專業映像',
    subtitle: '智能攝影工作室',
    uploadTitle: '素材來源',
    uploadDesc: '上傳原始照片',
    uploadTip: '需求：正面拍攝，光線充足。',
    changePhoto: '更換素材',
    genderLabel: '主體性別',
    male: '男士',
    female: '女士',
    clothingLabel: '造型指導',
    clothingPlaceholder: '描述期望風格 (例：訂製深藍西裝，硬挺白襯衫...)',
    clothingPresetsLabel: '精選造型',
    undo: '復原',
    redo: '重做',
    randomBtn: '隨機靈感',
    generateBtn: '開始生成',
    regenerateBtn: '重新生成',
    downloadBtn: '下載檔案',
    anglesTitle: '多角度運鏡',
    angleLeft45: '左側寫',
    angleRight45: '右側寫',
    angleFull: '全身景',
    angleClose: '面部特寫',
    historyTitle: '場景資產',
    emptyTitle: '工作室就緒',
    emptyDesc: '導入人像以開始專業造型製作。',
    errorNoImage: '請先導入照片。',
    errorApiKey: 'API 連線失敗。',
    errorEntityNotFound: '專案無效。',
    errorGeneric: '系統錯誤。',
    billingLinkText: '需使用付費金鑰 (Enterprise)',
    selectKeyBtn: '驗證金鑰',
    retryBtn: '重試連線',
    loading: '渲染中...',
    success: '生成完成',
    selectPreset: '選擇精選風格...',
    footerRights: '奧創集團控股有限公司 © 2025',
    ctaShareTitle: '專業作品集',
    ctaShareBtn: '匯出至藝廊'
  },
  'zh-CN': {
    title: 'Autron 专业映像',
    subtitle: '智能摄影工作室',
    uploadTitle: '素材来源',
    uploadDesc: '上传原始照片',
    uploadTip: '需求：正面拍摄，光线充足。',
    changePhoto: '更换素材',
    genderLabel: '主体性别',
    male: '男士',
    female: '女士',
    clothingLabel: '造型指导',
    clothingPlaceholder: '描述期望风格 (例：定制深蓝西装，硬挺白衬衫...)',
    clothingPresetsLabel: '精选造型',
    undo: '撤销',
    redo: '重做',
    randomBtn: '随机灵感',
    generateBtn: '开始生成',
    regenerateBtn: '重新生成',
    downloadBtn: '下载档案',
    anglesTitle: '多角度运镜',
    angleLeft45: '左侧写',
    angleRight45: '右侧写',
    angleFull: '全身景',
    angleClose: '面部特写',
    historyTitle: '场景资产',
    emptyTitle: '工作室就绪',
    emptyDesc: '导入人像以开始专业造型制作。',
    errorNoImage: '请先导入照片。',
    errorApiKey: 'API 连线失败。',
    errorEntityNotFound: '项目无效。',
    errorGeneric: '系统错误。',
    billingLinkText: '需使用付费密钥 (Enterprise)',
    selectKeyBtn: '验证密钥',
    retryBtn: '重试连线',
    loading: '渲染中...',
    success: '生成完成',
    selectPreset: '选择精选风格...',
    footerRights: '奥创集团控股有限公司 © 2025',
    ctaShareTitle: '专业作品集',
    ctaShareBtn: '汇出至艺廊'
  },
};